### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by 4dawit** [group48WEB103/ticketeller#2]
Replace the current root README with the template from https://github.com/codepath/web103_finalproject. For this week's submission, go to https://github.com/codepath/web103_finalproject/blob/main/milestones/milestone1.md and create a new folder in root called milestones to add this week's milestone, and make a pull request from the dev branch to update the main branch. Let me know if you have any questions.

**Comment by Zakariya-1221** [comment]
I added this week's milestone to the milestone folder I created in the root directory. Do you want me to fill in the description and purpose section? I'm not sure if we discussed what the app will do or if it is a continuation of your hotel finder application. Do you want to set up a Zoom call to go over?

**Comment by 4dawit** [comment]
Let's set up a zoom call, I'm free tonight. If not tonight, let me know when you can call.

**Comment by Zakariya-1221** [comment]
Sure I can set up a zoom call now. I'm in the EST time zone.

**Comment by 4dawit** [comment]
Sounds good, I'm in EST too.

**Comment by Zakariya-1221** [comment]
Here's the link: https://us05web.zoom.us/j/84276358914?pwd=0eycIHfcTp6Nk3jDYbT32u78g8MfNu.1

**Comment by Zakariya-1221** [comment]
new link https://meet.google.com/wqr-zykd-rtw

**Comment by 4dawit** [comment]
I'm going to replace the code in this repo with our new project idea, I'll also just finish the hotel idea and make sure it passes all the requirements for the final project so we can use it as a backup if we don't finish the ticketing idea on time.
